### ISSUE TITLE
Mauro's review

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.colours#10]
It looks great! I only have two nit comments:

1. I see a needless `return()` here: 
https://github.com/2DegreesInvesting/r2dii.colours/blob/1cfb783fa64954ef006945be350aa92829299df9/R/get_colours.R#L26

If you follow the tidyverse style guide then "only use return() 
for early returns. Otherwise, rely on R to return the result of
the last evaluated expression." 
-- https://style.tidyverse.org/functions.html?q=early%20re#return﻿

2. I see do.case here: 
https://github.com/2DegreesInvesting/r2dii.colours/tree/master/data

Are you using the S3 object system?

"It's better to reserve dots exclusively for the S3 object system. In
S3, methods are given the name `function.class`; if you also use `.`
in function and class names, you end up with confusing methods like
`as.data.frame.data.frame()`". -- https://style.tidyverse.org/syntax.html?q=snake#object-names

Nice to have:

3. A website: Run 

```r
usethis::use_pkgdown()
usethis::use_pkgdown_github_pages()
```

**Comment by MonikaFu** [comment]
Thanks! All useful

**Comment by MonikaFu** [comment]
Solved with #14
